### PR TITLE
docs: SNS + SQS integration notes

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Proposal to Close https://github.com/localstack/docs/issues/511

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
Question. Is there a way to view the preview myself?

I tried to follow conventions in the existing document, but I don't actually know how to preview this.

**Comment by Lewiscowles1986** [comment]
I have now checked locally. It looks to be the same style.

It does take from 4 minute estimated reading to 5 minute estimated reading.

This is only my second foray into Hugo, so if it needs to come out to move elsewhere I might need support with what that would look like.

My passionate plea is that quite a lot of third-parties cover SNS + SQS, but the pieces are not that clear. By signposting someone in your docs, you enable them to both complete the task, but also understand the high-level steps.

**Review by bentsku — COMMENTED** [review]
Hi @Lewiscowles1986 and thanks for your contribution!

It's definitely a great idea to add more samples and ways to get started with SNS and SQS.
I'd like to also have the responses from the command, so it would be a bit easier to read and follow where the resources come from (the ARN, the queue URL...).

I'd like to have your opinion @HarshCasper on the format.

On the content level, we maybe should set a Policy on the queue so that the SNS topic is able to publish to it. It is not enforced by LocalStack at the moment, but it could be good to mention it and maybe show how it should be done so that the sample is also working against AWS (maybe with a comment that it's not necessary? What do you think @HarshCasper? Maybe mentioning it and linking to https://docs.aws.amazon.com/sns/latest/dg/subscribe-sqs-queue-to-sns-topic.html would be enough.)

**Comment by thrau** [comment]
since there hasn't been any movement on this, i took the liberty of pushing some changes that also @bentsku suggested, resolved merge conflicts, and will merge this once green. thanks for the contribution Lewis @Lewiscowles1986, and sorry we've been sitting on this for so long, it somehow slipped through the cracks

**Comment by Lewiscowles1986** [comment]
@thrau I'm also sorry, as I think I forgot to make some changes.

**Pull request merged**
