### PR TITLE
Split EKS commands and outputs for better copy and paste

### PR DESCRIPTION
**Pull request by simonrw**
# Motivation

When starting an EKS cluster, I was copying the commands from the docs but the output was copied along with the commands.

# Changes

* Split the command and output into separate code blocks

### CODE REVIEW

**Review by alexrashed — COMMENTED** [review]
Great that you are changing the docs right when coming across issues!
For some of the changes in the PR it might make sense to use the new feature @webdev51 implemented: https://github.com/localstack/docs/pull/804#discussion_r1315160963
Wit that you can disable the copying for certain sections within the command, instead of separating command and output all the time (which sometimes makes sense, but sometimes disrupts the flow).

**Comment by simonrw** [comment]
> Great that you are changing the docs right when coming across issues! For some of the changes in the PR it might make sense to use the new feature @webdev51 implemented: [#804 (comment)](https://github.com/localstack/docs/pull/804#discussion_r1315160963) Wit that you can disable the copying for certain sections within the command, instead of separating command and output all the time (which sometimes makes sense, but sometimes disrupts the flow).

Thanks @alexrashed for the suggestion. I definitely prefer the output as rendered, however the copied command contains a newline at the end. An alternative is to do something like

```markdown
{{< command >}}
$ pwd<disable-copy>
/
</disable-copy>
{{< / command >}}
```

which is a little ugly, but in general I prefer to not break up the reading flow as you say.

**Comment by alexrashed** [comment]
Ah, interesting. A newline at the end really doesn't seem to be too nice when copy-pasting the commands.
Maybe we could fix the command shortcode to suppress the last newline?
Should be fixed somewhere around this line:
https://github.com/localstack/docs/blob/main/layouts/shortcodes/command.html#L6

**Comment by simonrw** [comment]
> Ah, interesting. A newline at the end really doesn't seem to be too nice when copy-pasting the commands. Maybe we could fix the command shortcode to suppress the last newline?

[I have implemented this by trimming the whitespace from the copied text before sending to the clipboard](https://github.com/localstack/docs/pull/841/commits/d634eec251eeb8770c0d9a8d495c57f8d3cd0b14).

**Review by alexrashed — APPROVED** [review]
Awesome! 💯

**Pull request merged**
